server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server: # Fix for upgrade: added nodes server.webflux. Diff for webflux or webmvc
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            # Route to user-service
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=0

            # Route to order-service
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - StripPrefix=0

            # Route to ai-service
            - id: ai-service
              uri: lb://ai-service
              predicates:
                - Path=/api/ai/**
              filters:
                - StripPrefix=0
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin123}@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  prometheus:
    metrics:
      export:
        enabled: true
springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs				
      - name: ai-service
        url: /ai-service/v3/api-docs				
jwt:
  # Signing Key(not the signature itself). openssl rand -base64 32
  # Signature(HMAC-SHA256(header.payload, secretKey)) = Header + Payload + secretKey
  # Header By {"alg": "HS256", "typ": "JWT"}
  # Payload By .subject(email).issuedAt(...).expiration(...)
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # milliseconds, 60000 ms/ 1 minute,3600000 ms/ 1 hour, 86400000 ms/ 24 hours

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR