server:
  port: 8083

spring:
  application:
    name: ai-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:raguser}
    password: ${DB_PASSWORD:ragpass123}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # none,create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1:latest # llama3.1:8b # llama3.2:3b,
          temperature: 0.3 # lower temperature for more deterministic responses, higher for more creative responses. range: 0.0 - 1.0
          num-predict: 2048 # increase for longer responses, decrease for faster responses
      embedding: # for embedding generation, you can use a different model if needed
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector: # postgres plugin for vector storage
        index-type: hnsw # (Hierarchical Navigable Small World)
        distance-type: cosine_distance # (Cosine Similarity)
        dimensions: 768 # Must match the embedding model's output dimensions with 'nomic-embed-text' model
        initialize-schema: true # like create table if not exists, set to false if you already have the schema created

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin123}@localhost:8761/eureka/
  instance:
    prefer-ip-address: false # true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers
  endpoint:
    health:
      # show-details: when-authorized # always
      show-components: always
  health:
    diskspace:
      enabled: false
logging:
  level:
    com.demo.ai: DEBUG
#    org.springframework.ai.chat.client.advisor: DEBUG
    root: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR