server:
  port: 8083

spring:
  application:
    name: ai-service
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.1:8b # llama3.2:3b

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: false # true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info